from config.db_connection import DatabaseConnection
from models.user import User
from mysql.connector import Error


class UserRepository:
    """
    Handles all database operations (CRUD) for the User entity.
    Acts as a bridge between the English Python object and the French SQL database.
    """

    @staticmethod
    def create(user: User):
        """
        Inserts a new user into the database.
        Returns the User object updated with the newly generated ID.
        """
        connection = DatabaseConnection.get_connection()
        if not connection:
            print("❌ Database connection failed.")
            return None

        try:
            cursor = connection.cursor()

            # The SQL query uses French column names to match the database schema
            # We use %s to prevent SQL injection (never use f-strings for SQL variables!)
            sql = """
                  INSERT INTO utilisateur
                      (email, password, prenom, nom, pays, role_id)
                  VALUES (%s, %s, %s, %s, %s, %s) \
                  """

            # Mapping the English object attributes to the query values
            values = (
                user.email,
                user.password,  # In a real app, this MUST be hashed before arriving here!
                user.first_name,
                user.last_name,
                user.country,
                user.role_id
            )

            cursor.execute(sql, values)
            connection.commit()  # Save the changes to the database

            # Retrieve the auto-incremented ID generated by MySQL
            user.user_id = cursor.lastrowid
            print(f"✅ User successfully created with ID: {user.user_id}")

            return user

        except Error as e:
            print(f"❌ Error while creating user: {e}")
            return None

        finally:
            # Always close the cursor and connection to free up resources
            if connection.is_connected():
                cursor.close()
                connection.close()

    @staticmethod
    def get_by_email(email: str):
        """
        Retrieves a user from the database using their email.
        Returns a User object, or None if not found.
        """
        connection = DatabaseConnection.get_connection()
        if not connection:
            return None

        try:
            # dictionary=True allows retrieving rows as dictionaries instead of tuples
            cursor = connection.cursor(dictionary=True)
            sql = "SELECT * FROM utilisateur WHERE email = %s"
            cursor.execute(sql, (email,))

            row = cursor.fetchone()

            if row:
                # Translating the French SQL row back into an English Python User object
                return User(
                    user_id=row['utilisateur_id'],
                    email=row['email'],
                    password=row['password'],
                    first_name=row['prenom'],
                    last_name=row['nom'],
                    country=row['pays'],
                    is_active=row['est_actif'],
                    created_at=row['date_creation'],
                    role_id=row['role_id']
                )
            return None

        except Error as e:
            print(f"❌ Error while fetching user: {e}")
            return None

        finally:
            if connection.is_connected():
                cursor.close()
                connection.close()