### 1. Inscription d'un nouvel utilisateur de test
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "postman@omnisave.test",
  "password": "Password123!"
}

### 2. Connexion (Pour récupérer le JWT Token)
# ⚠️ COPIE LE TOKEN REÇU DANS LA RÉPONSE
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "postman@omnisave.test",
  "password": "Password123!"
}


### --- NOUVEAU FLUX DE CRÉATION ---

### 3a. Prévisualisation d'un lien (L'IA analyse mais ne sauvegarde pas)
POST http://localhost:5000/api/links/preview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE3ODkzOTk3MTgsImlhdCI6MTc4OTMxMzMxOH0.NlYHvlA7mEGYCCtGwLRSBpwr1m74i5TIbZ92d8I-wE0

{
  "url": "https://www.instagram.com/reels/DdHV-EeodO7/"
}

### 3b. Sauvegarde finale d'un lien (Après validation du tiroir)
POST http://localhost:5000/api/links
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE3ODkzOTk3MTgsImlhdCI6MTc4OTMxMzMxOH0.NlYHvlA7mEGYCCtGwLRSBpwr1m74i5TIbZ92d8I-wE0

{
  "url": "https://www.instagram.com/reels/DdHV-EeodO7/",
  "title": "Vidéo Instagram incroyable",
  "category": "Sport",
  "tags": ["sport", "instagram", "test"]
}


### --- RÉCUPÉRATION ET MODIFICATION ---

### 4. Récupérer tous les liens de l'utilisateur
GET http://localhost:5000/api/links
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE3ODkzOTk3MTgsImlhdCI6MTc4OTMxMzMxOH0.NlYHvlA7mEGYCCtGwLRSBpwr1m74i5TIbZ92d8I-wE0


### 5. 🆕 MODIFIER UN LIEN (Remplace le "1" à la fin par un vrai ID de ta base)
PUT http://localhost:5000/api/links/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE3ODkzOTk3MTgsImlhdCI6MTc4OTMxMzMxOH0.NlYHvlA7mEGYCCtGwLRSBpwr1m74i5TIbZ92d8I-wE0

{
  "title": "Titre super modifié depuis le test HTTP !",
  "category": "Cooking",
  "tags": ["tag-modifié", "mise-a-jour", "succes"]
}

### --- GESTION DU PROFIL ---

### 6. Récupérer son profil
GET http://localhost:5000/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3ODk0MDIxNDQsImlhdCI6MTc4OTMxNTc0NH0.h4aQn1kdAqm5OQK48IlzRvfSsZQKlFoj-gAQqzCZqug


### 7. Modifier son profil (Prénom, Nom, Pseudo, Fast-Save, Pays)
PUT http://localhost:5000/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3ODk0MDIxNDQsImlhdCI6MTc4OTMxNTc0NH0.h4aQn1kdAqm5OQK48IlzRvfSsZQKlFoj-gAQqzCZqug

{
  "first_name": "Anthony",
  "last_name": "Mula",
  "pseudo": "Anthodev",
  "fast_save": true,
  "country": "France"
}


### 8. Supprimer son compte (Efface l'utilisateur et tous ses liens)
DELETE http://localhost:5000/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3ODk0MDIxNDQsImlhdCI6MTc4OTMxNTc0NH0.h4aQn1kdAqm5OQK48IlzRvfSsZQKlFoj-gAQqzCZqug